version: 1
services:
- name: frontend
  containers:
  - name: frontend
    image: tomaskral/kompose-demo-frontend:test
    env:
    - KEY=value
    - KEY2=value2
    mappings:
    - port: 5000:8080:80
    - port: 5001:8081:81
volumes:
- name: data
  size: 1Gi
  mode: ReadWriteOnce

